import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Toaster } from 'react-hot-toast';
import { Providers } from './providers';

const dm_sans = DM_Sans({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
// TODO: Add all SEO shit
console.log(dm_sans.style.fontFamily);
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={dm_sans.className}>
			<head>
				<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
			</head>
			<body>
				<Providers>{children}</Providers>
				<Toaster />
				<GoogleAnalytics gaId="G-DJNEVNJYM7" />
			</body>
		</html>
	);
}
